# Generated by Django 5.2.10 on 2026-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videolesson_order_course_videolesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='courses/'),
        ),
    ]
