# Generated by Django 5.2.10 on 2026-01-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='videos.course'),
        ),
    ]
