# Generated by Django 5.2.10 on 2026-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_videolesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
