# Generated by Django 5.2.10 on 2026-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videolesson_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='videos/'),
        ),
    ]
